services:
  aplikasi-penilaian-franken:
    container_name: aplikasi-penilaian-franken
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - SERVER_NAME=:80
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8008:80"
    volumes:
      - .:/app
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - .:/var/www/html
    networks:
      - default
      - mysql-stack_mysql_network

  aplikasi-penilaian-worker:
    container_name: aplikasi-penilaian-worker
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    # Menjalankan worker dengan 3x percobaan (sesuai setting job)
    command: php artisan queue:work --tries=3 --backoff=60
    volumes:
      - .:/app
      - .:/var/www/html
    networks:
      - default
      - mysql-stack_mysql_network
    depends_on:
      - aplikasi-penilaian-franken

networks:
  default: {}
  mysql-stack_mysql_network:
    external: true
